In [55]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup as bs
from time import sleep
from datetime import datetime
from splinter import Browser
from selenium.webdriver.common.keys import Keys
import time
import json
import os
import shutil

In [56]:
# Path to chromedriver.exe
executable_path = {'executable_path':'C:/Users/zacha/AppData/Local/bin/chromedriver.exe'}

# Open the Splinter Browswer
browser = Browser('chrome', **executable_path)

In [57]:
# URL to find information on Coronavirus
url1 = "https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83"

url2 = "https://dshs.texas.gov/coronavirus/"

url3 = "http://publichealth.harriscountytx.gov/Resources/2019-Novel-Coronavirus/Harris-County-COVID-19-Confirmed-Cases"

url4 = "https://www.khou.com/section/news/health/coronavirus"

In [58]:
# Visiting the url 
browser.visit(url1)

In [59]:
time.sleep(7)# Creating the Beautiful soup for URL
html = browser.html
soup = bs(html, 'html.parser')

In [60]:
# All the Texas counties
# counties = soup.find('nav', attrs={'class':'feature-list'})

# getting all the spans with the information for each Texas county
# rows = counties.find_all('span')

In [61]:
# counter = 0

# county = []
# cases = []

# for row in rows:
#     try:
#         print(rows[counter].text.strip().split('\n'))
#         county.append(rows[counter].text.strip().split('\n')[0])
#         cases.append(rows[counter].text.strip().split('\n')[1])
#         counter = counter + 3
        
#     except:
#         print('failure')

In [62]:
# df = pd.DataFrame(list(zip(county, cases)), columns =['Texas_County', 'COVID_19_Cases'])
# df

In [63]:
# Droping the word 'County'
# df['Texas_County'] = df['Texas_County'].apply(lambda x : x.split(' County')[0])

In [64]:
# Revise? 
reported_cases = soup.find_all('text')[6].text
reported_cases

'6,110'

In [65]:
deaths = soup.find_all('text')[8].text
deaths

'105'

In [66]:
df_stats = pd.DataFrame({'Cases':[reported_cases], 'Deaths':[deaths]})
df_stats.to_csv('static/csv/stats.csv', index=False)

In [67]:
# Getting Total Cases and Deaths 
browser.visit(url2)

In [68]:
browser.find_by_text('Accessible version').click()
time.sleep(5)

In [69]:
source = 'C:/Users/zacha/Downloads/'
destination = 'C:/Users/zacha/Documents/COVID-19/'
filename = 'CaseCountData.xlsx'

In [70]:
shutil.move(os.path.join(source, filename), os.path.join(destination, filename))

'C:/Users/zacha/Documents/COVID-19/CaseCountData.xlsx'

In [71]:
# dest = shutil.move(source, destination, )

In [72]:
df = pd.read_excel('CaseCountData.xlsx', header=1).dropna()
df.sort_values(by=['Positive'], ascending=False, inplace=True)
df['County'] = df.apply(lambda x: x['County'].rstrip(), axis=1)
df

       No.       County  Positive  Fatalities
58    59.0       Harris      1106          13
30    31.0       Dallas       921          17
131  132.0       Travis       430           4
126  127.0      Tarrant       383           7
7      8.0        Bexar       342           9
..     ...          ...       ...         ...
129  130.0        Titus         1           0
1      2.0      Andrews         1           0
125  126.0      Swisher         1           0
120  121.0  San Jacinto         1           0
0      1.0     Anderson         1           0

[151 rows x 4 columns]

In [73]:
browser.visit(url3)

In [74]:
harris_table = browser.find_by_id('covidtable')

In [75]:
html_harris = browser.html
harris_soup = bs(html_harris, 'html.parser')

In [76]:
harris_data = []
table = harris_soup.find('table', attrs={'id':'covidtable'})
table_body = table.find('tbody')

rows = table_body.find_all('tr')
for row in rows:
    cols = row.find_all('td')
    cols = [ele.text.strip() for ele in cols]
    harris_data.append([ele for ele in cols if ele]) # Get rid of empty values

In [77]:
columns = ['Patient', 'Sex', 'Age_Range', 'Location','Exposure', 'Status']

In [78]:
harris_data = harris_data[1:]

In [79]:
harris_df = pd.DataFrame(harris_data, columns=columns)

In [80]:
harris_df.sort_values(by=['Age_Range'], inplace=True)

In [81]:
harris_df

    Patient     Sex Age_Range Location                   Exposure    Status
43       44    Male     0 - 9       NW  Possible Exposure to Case    Active
45       46  Female     0 - 9       NW  Possible Exposure to Case    Active
172     173  Female     0 - 9       NW  Possible Exposure to Case    Active
185     186  Female     0 - 9       SE  Possible Exposure to Case    Active
147     148    Male   10 - 19       SE  Possible Exposure to Case    Active
..      ...     ...       ...      ...                        ...       ...
154     155  Female       80+       SE      Investigation Pending    Active
246     247  Female       80+       SW      Investigation Pending    Active
15       16    Male       80+       NW          No Known Exposure  Deceased
158     159  Female       80+       NW          History of Travel    Active
193     194  Female       80+       SE          No Known Exposure    Active

[254 rows x 6 columns]

In [82]:
harris_df.to_csv('static/csv/harris_stats.csv', index=False, header=True)

In [83]:
harris_df.head()

    Patient     Sex Age_Range Location                   Exposure  Status
43       44    Male     0 - 9       NW  Possible Exposure to Case  Active
45       46  Female     0 - 9       NW  Possible Exposure to Case  Active
172     173  Female     0 - 9       NW  Possible Exposure to Case  Active
185     186  Female     0 - 9       SE  Possible Exposure to Case  Active
147     148    Male   10 - 19       SE  Possible Exposure to Case  Active

In [84]:
All_Tex_Counties_df = pd.read_csv('static/csv/Texas_Counties.csv')
All_Tex_Counties_df.head()

,X (Lat),Y (Long),CNTY_NM,CNTY_NBR,FIPS,Shape_Leng,Shape_Area,County Location
0,-97.492799,29.456415,Gonzales,90,48177,2.124911,0.257805,"(-97.492799, 29.456415)"
1,-98.697292,27.043405,Jim Hogg,125,48247,2.271751,0.267624,"(-98.697292, 27.043405)"
2,-97.681378,26.924094,Kenedy,66,48261,5.067864,0.389397,"(-97.681378, 26.924094)"
3,-96.965687,30.310651,Lee,144,48287,2.213853,0.153990,"(-96.965687, 30.310651)"
4,-95.853568,32.211881,Henderson,108,48213,3.152909,0.235056,"(-95.853568, 32.211881)"

In [85]:
All_Tex_Counties = All_Tex_Counties_df['CNTY_NM'].tolist()

In [86]:
df_counties = df['County'].tolist()

In [87]:
Counties_with_Cases = []

for i in df_counties:
    
    if i.rstrip() in All_Tex_Counties:
        Counties_with_Cases.append(i.rstrip())
        print(f'{i}---found')
        
    elif i == 'DeWitt':
        Counties_with_Cases.append('De Witt')
        print(f'{i}---found')
    else:
        print(f'Houston we have a problem: {i}')

Harris---found
Dallas---found
Travis---found
Tarrant---found
Bexar---found
Denton---found
Collin---found
Fort Bend---found
Lubbock---found
Galveston---found
Brazoria---found
Montgomery---found
El Paso---found
Hidalgo---found
Webb---found
Brazos---found
Williamson---found
Cameron---found
Smith---found
Bell---found
McLennan---found
Nueces---found
Hays---found
Wichita---found
Matagorda---found
Victoria---found
Ellis---found
Jefferson---found
Guadalupe---found
Randall---found
Potter---found
Taylor---found
Midland---found
Ector---found
Johnson---found
Comal---found
Bowie---found
Washington---found
Tom Green---found
Nacogdoches---found
Hardin---found
Gregg---found
Orange---found
Grayson---found
Rusk---found
Rockwall---found
Shelby---found
Chambers---found
Fayette---found
Kaufman---found
Castro---found
Angelina---found
Hood---found
Wharton---found
Kendall---found
Waller---found
Hunt---found
Calhoun---found
Walker---found
Polk---found
Hockley---found
Erath---found
Bastrop---found
Moore---found
Wilson---found
Parker---found
DeWitt---found
Hale---found
Starr---found
Liberty---found
Lamar---found
Harrison---found
Donley---found
Cherokee---found
Navarro---found
Gray---found
Val Verde---found
Willacy---found
Hill---found
Deaf Smith---found
Terry---found
Maverick---found
Panola---found
Coryell---found
San Patricio---found
Cass---found
San Augustine---found
Austin---found
Uvalde---found
Burnet---found
Brown---found
Van Zandt---found
Medina---found
Young---found
Lynn---found
Llano---found
Live Oak---found
Limestone---found
Jackson---found
Hopkins---found
Upshur---found
Eastland---found
Dawson---found
Caldwell---found
Wise---found
Grimes---found
Robertson---found
Trinity---found
Karnes---found
Oldham---found
Kleberg---found
Atascosa---found
Blanco---found
Burleson---found
Colorado---found
Crane---found
Fannin---found
Gillespie---found
Jasper---found
Jim Wells---found
Kerr---found
Hutchinson---found
Leon---found
Lavaca---found
Lee---found
Milam---found
Franklin---found
Wood---found
Newton---found
Morris---found
Montague---found
Camp---found
Clay---found
Comanche---found
Mason---found
Falls---found
Martin---found
Lamb---found
Gaines---found
Lampasas---found
Goliad---found
Gonzales---found
Tyler---found
Hemphill---found
Henderson---found
Palo Pinto---found
Titus---found
Andrews---found
Swisher---found
San Jacinto---found
Anderson---found

In [88]:
All_Tex_Counties_df = All_Tex_Counties_df.set_index('CNTY_NM')

In [89]:
Geo_df = All_Tex_Counties_df.loc[Counties_with_Cases]
Geo_df.head()

,X (Lat),Y (Long),CNTY_NBR,FIPS,Shape_Leng,Shape_Area,County Location
CNTY_NM,,,,,,,
Harris,-95.397821,29.859671,102,48201,7.731110,0.422798,"(-95.397821, 29.859671)"
Dallas,-96.777819,32.766537,57,48113,1.907782,0.226421,"(-96.777819, 32.766537)"
Travis,-97.781947,30.334233,227,48453,2.458272,0.248996,"(-97.781947, 30.334233)"
Tarrant,-97.291165,32.771852,220,48439,1.905740,0.225294,"(-97.291165, 32.771852)"
Bexar,-98.519663,29.448845,15,48029,2.729791,0.302846,"(-98.519663, 29.448845)"

In [90]:
Geo_df = Geo_df.reset_index()
Geo_df = Geo_df.rename(columns={"CNTY_NM": "County"})
Geo_df

,County,X (Lat),Y (Long),CNTY_NBR,FIPS,Shape_Leng,Shape_Area,County Location
0,Harris,-95.397821,29.859671,102,48201,7.731110,0.422798,"(-95.397821, 29.859671)"
1,Dallas,-96.777819,32.766537,57,48113,1.907782,0.226421,"(-96.777819, 32.766537)"
2,Travis,-97.781947,30.334233,227,48453,2.458272,0.248996,"(-97.781947, 30.334233)"
3,Tarrant,-97.291165,32.771852,220,48439,1.905740,0.225294,"(-97.291165, 32.771852)"
4,Bexar,-98.519663,29.448845,15,48029,2.729791,0.302846,"(-98.519663, 29.448845)"
...,...,...,...,...,...,...,...,...
146,Titus,-94.965098,33.216091,225,48449,2.003081,0.106914,"(-94.965098, 33.216091)"
147,Andrews,-102.637884,32.305063,2,48003,2.579602,0.372269,"(-102.637884, 32.305063)"
148,Swisher,-101.734951,34.530650,219,48437,1.924577,0.229376,"(-101.734951, 34.53065)"
149,San Jacinto,-95.166833,30.579489,204,48407,2.203357,0.153019,"(-95.166833, 30.579489)"
150,Anderson,-95.652518,31.813215,1,48001,3.709381,0.265992,"(-95.652518, 31.813215)"

In [91]:
result = pd.merge(df, Geo_df, on='County')
result = result.rename(columns={'X (Lat)':'long', 'Y (Long)':'lat'})

result.head()

,No.,County,Positive,Fatalities,long,lat,CNTY_NBR,FIPS,Shape_Leng,Shape_Area,County Location
0,59.0,Harris,1106,13,-95.397821,29.859671,102,48201,7.731110,0.422798,"(-95.397821, 29.859671)"
1,31.0,Dallas,921,17,-96.777819,32.766537,57,48113,1.907782,0.226421,"(-96.777819, 32.766537)"
2,132.0,Travis,430,4,-97.781947,30.334233,227,48453,2.458272,0.248996,"(-97.781947, 30.334233)"
3,127.0,Tarrant,383,7,-97.291165,32.771852,220,48439,1.905740,0.225294,"(-97.291165, 32.771852)"
4,8.0,Bexar,342,9,-98.519663,29.448845,15,48029,2.729791,0.302846,"(-98.519663, 29.448845)"

In [92]:
result = result[['County', 'Positive', 'Fatalities', 'lat', 'long']]
result

          County  Positive  Fatalities        lat        long
0         Harris      1106          13  29.859671  -95.397821
1         Dallas       921          17  32.766537  -96.777819
2         Travis       430           4  30.334233  -97.781947
3        Tarrant       383           7  32.771852  -97.291165
4          Bexar       342           9  29.448845  -98.519663
..           ...       ...         ...        ...         ...
145        Titus         1           0  33.216091  -94.965098
146      Andrews         1           0  32.305063 -102.637884
147      Swisher         1           0  34.530650 -101.734951
148  San Jacinto         1           0  30.579489  -95.166833
149     Anderson         1           0  31.813215  -95.652518

[150 rows x 5 columns]

In [93]:
def df_to_geojson(df, properties, lat='lat', lon='long'):
    prefix = 'var' + ' data' + ' = '
    geojson = {'type':'FeatureCollection', 'features':[]}
    for _, row in df.iterrows():
        feature = {'type':'Feature',
                   'properties':{},
                   'geometry':{'type':'Point','coordinates':[]}}
        feature['geometry']['coordinates'] = [row[lat],row[lon]]
        for prop in properties:
            feature['properties'][prop] = row[prop]
        geojson['features'].append(feature)
    return geojson

cols = ['County', 'Positive', 'Fatalities']
javascript_file = df_to_geojson(result, cols)
# {'type': 'FeatureCollection', 'features': [{'geometry': {'type': 'Point', 'coordinates': [-70.5867, -29.9953, 760]}, 'type': 'Feature', 'properties': {'name': 'A', 'description': 'Place a'}}, {'geometry': {'type': 'Point', 'coordinates': [-70.4933, -30.1217, 1250]}, 'type': 'Feature', 'properties': {'name': 'B', 'description': 'Place b'}}, {'geometry': {'type': 'Point', 'coordinates': [-70.5008, -30.0953, 1185]}, 'type': 'Feature', 'properties': {'name': 'C', 'description': 'Place c'}}]}

In [94]:
javascript_file

{'type': 'FeatureCollection',
 'features': [{'type': 'Feature',
   'properties': {'County': 'Harris', 'Positive': 1106, 'Fatalities': 13},
   'geometry': {'type': 'Point', 'coordinates': [29.85967144, -95.39782106]}},
  {'type': 'Feature',
   'properties': {'County': 'Dallas', 'Positive': 921, 'Fatalities': 17},
   'geometry': {'type': 'Point', 'coordinates': [32.76653746, -96.77781862]}},
  {'type': 'Feature',
   'properties': {'County': 'Travis', 'Positive': 430, 'Fatalities': 4},
   'geometry': {'type': 'Point', 'coordinates': [30.33423319, -97.78194654]}},
  {'type': 'Feature',
   'properties': {'County': 'Tarrant', 'Positive': 383, 'Fatalities': 7},
   'geometry': {'type': 'Point', 'coordinates': [32.77185236, -97.29116473]}},
  {'type': 'Feature',
   'properties': {'County': 'Bexar', 'Positive': 342, 'Fatalities': 9},
   'geometry': {'type': 'Point', 'coordinates': [29.44884523, -98.51966309]}},
  {'type': 'Feature',
   'properties': {'County': 'Denton', 'Positive': 273, 'Fatalities': 6},
   'geometry': {'type': 'Point', 'coordinates': [33.205574, -97.11681154]}},
  {'type': 'Feature',
   'properties': {'County': 'Collin', 'Positive': 256, 'Fatalities': 2},
   'geometry': {'type': 'Point', 'coordinates': [33.18789055, -96.57248871]}},
  {'type': 'Feature',
   'properties': {'County': 'Fort Bend', 'Positive': 255, 'Fatalities': 2},
   'geometry': {'type': 'Point', 'coordinates': [29.52763253, -95.77090562]}},
  {'type': 'Feature',
   'properties': {'County': 'Lubbock', 'Positive': 138, 'Fatalities': 4},
   'geometry': {'type': 'Point', 'coordinates': [33.6101944, -101.8205745]}},
  {'type': 'Feature',
   'properties': {'County': 'Galveston', 'Positive': 136, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [29.39424415, -94.96474975]}},
  {'type': 'Feature',
   'properties': {'County': 'Brazoria', 'Positive': 136, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [29.19345387, -95.45578479]}},
  {'type': 'Feature',
   'properties': {'County': 'Montgomery', 'Positive': 130, 'Fatalities': 3},
   'geometry': {'type': 'Point', 'coordinates': [30.30022409, -95.50301411]}},
  {'type': 'Feature',
   'properties': {'County': 'El Paso', 'Positive': 96, 'Fatalities': 0},
   'geometry': {'type': 'Point',
    'coordinates': [31.768622600000004, -106.23522290000001]}},
  {'type': 'Feature',
   'properties': {'County': 'Hidalgo', 'Positive': 86, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [26.396627, -98.18088681]}},
  {'type': 'Feature',
   'properties': {'County': 'Webb', 'Positive': 83, 'Fatalities': 5},
   'geometry': {'type': 'Point', 'coordinates': [27.76102524, -99.33170164]}},
  {'type': 'Feature',
   'properties': {'County': 'Brazos', 'Positive': 72, 'Fatalities': 5},
   'geometry': {'type': 'Point', 'coordinates': [30.6610425, -96.3022943]}},
  {'type': 'Feature',
   'properties': {'County': 'Williamson', 'Positive': 71, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [30.64834941, -97.60105467]}},
  {'type': 'Feature',
   'properties': {'County': 'Cameron', 'Positive': 62, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [26.13847728, -97.51499968]}},
  {'type': 'Feature',
   'properties': {'County': 'Smith', 'Positive': 57, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [32.37514553, -95.26909511]}},
  {'type': 'Feature',
   'properties': {'County': 'Bell', 'Positive': 51, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [31.03778267, -97.47790776]}},
  {'type': 'Feature',
   'properties': {'County': 'McLennan', 'Positive': 50, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [31.55234489, -97.20184883]}},
  {'type': 'Feature',
   'properties': {'County': 'Nueces', 'Positive': 47, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [27.72621549, -97.61767326]}},
  {'type': 'Feature',
   'properties': {'County': 'Hays', 'Positive': 47, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [30.05782657, -98.03104087]}},
  {'type': 'Feature',
   'properties': {'County': 'Wichita', 'Positive': 46, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [33.98421585, -98.70153389]}},
  {'type': 'Feature',
   'properties': {'County': 'Matagorda', 'Positive': 33, 'Fatalities': 2},
   'geometry': {'type': 'Point', 'coordinates': [28.86711039, -95.98533866]}},
  {'type': 'Feature',
   'properties': {'County': 'Victoria', 'Positive': 32, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [28.79640594, -96.97176602]}},
  {'type': 'Feature',
   'properties': {'County': 'Ellis', 'Positive': 29, 'Fatalities': 2},
   'geometry': {'type': 'Point', 'coordinates': [32.34839264, -96.79467417]}},
  {'type': 'Feature',
   'properties': {'County': 'Jefferson', 'Positive': 29, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [29.88425832, -94.1708778]}},
  {'type': 'Feature',
   'properties': {'County': 'Guadalupe', 'Positive': 26, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [29.58257236, -97.94850308]}},
  {'type': 'Feature',
   'properties': {'County': 'Randall', 'Positive': 24, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [34.96594288, -101.8968527]}},
  {'type': 'Feature',
   'properties': {'County': 'Potter', 'Positive': 24, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [35.40128927, -101.8940484]}},
  {'type': 'Feature',
   'properties': {'County': 'Taylor', 'Positive': 23, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [32.30138229, -99.89003941]}},
  {'type': 'Feature',
   'properties': {'County': 'Midland', 'Positive': 22, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [31.86921148, -102.0315032]}},
  {'type': 'Feature',
   'properties': {'County': 'Ector', 'Positive': 22, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [31.86908156, -102.5430907]}},
  {'type': 'Feature',
   'properties': {'County': 'Johnson', 'Positive': 21, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [32.37899918, -97.36660504]}},
  {'type': 'Feature',
   'properties': {'County': 'Comal', 'Positive': 18, 'Fatalities': 2},
   'geometry': {'type': 'Point', 'coordinates': [29.80816362, -98.27814516]}},
  {'type': 'Feature',
   'properties': {'County': 'Bowie', 'Positive': 17, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [33.44572786, -94.42324298]}},
  {'type': 'Feature',
   'properties': {'County': 'Washington', 'Positive': 17, 'Fatalities': 0},
   'geometry': {'type': 'Point',
    'coordinates': [30.2145299, -96.40356575000001]}},
  {'type': 'Feature',
   'properties': {'County': 'Tom Green', 'Positive': 17, 'Fatalities': 0},
   'geometry': {'type': 'Point',
    'coordinates': [31.404444199999997, -100.4620678]}},
  {'type': 'Feature',
   'properties': {'County': 'Nacogdoches', 'Positive': 15, 'Fatalities': 2},
   'geometry': {'type': 'Point', 'coordinates': [31.61604108, -94.6158776]}},
  {'type': 'Feature',
   'properties': {'County': 'Hardin', 'Positive': 14, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [30.33238431, -94.39021394]}},
  {'type': 'Feature',
   'properties': {'County': 'Gregg', 'Positive': 13, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [32.48036452, -94.81723694]}},
  {'type': 'Feature',
   'properties': {'County': 'Orange', 'Positive': 12, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [30.12807126, -93.89653794]}},
  {'type': 'Feature',
   'properties': {'County': 'Grayson', 'Positive': 12, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [33.62684371, -96.67764864]}},
  {'type': 'Feature',
   'properties': {'County': 'Rusk', 'Positive': 11, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [32.10803224, -94.76169577]}},
  {'type': 'Feature',
   'properties': {'County': 'Rockwall', 'Positive': 11, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [32.89786769, -96.40780584]}},
  {'type': 'Feature',
   'properties': {'County': 'Shelby', 'Positive': 11, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [31.79242191, -94.14495261]}},
  {'type': 'Feature',
   'properties': {'County': 'Chambers', 'Positive': 11, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [29.73912276, -94.60891308]}},
  {'type': 'Feature',
   'properties': {'County': 'Fayette', 'Positive': 10, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [29.87683207, -96.91968047]}},
  {'type': 'Feature',
   'properties': {'County': 'Kaufman', 'Positive': 10, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [32.59927808, -96.28779341]}},
  {'type': 'Feature',
   'properties': {'County': 'Castro', 'Positive': 10, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [34.53000304, -102.2617608]}},
  {'type': 'Feature',
   'properties': {'County': 'Angelina', 'Positive': 10, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [31.25475875, -94.611742]}},
  {'type': 'Feature',
   'properties': {'County': 'Hood', 'Positive': 9, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [32.43107878, -97.83280338]}},
  {'type': 'Feature',
   'properties': {'County': 'Wharton', 'Positive': 9, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [29.2778362, -96.22197375]}},
  {'type': 'Feature',
   'properties': {'County': 'Kendall', 'Positive': 9, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [29.9446397, -98.71160511]}},
  {'type': 'Feature',
   'properties': {'County': 'Waller', 'Positive': 8, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [30.01093722, -95.98768942]}},
  {'type': 'Feature',
   'properties': {'County': 'Hunt', 'Positive': 8, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [33.123531, -96.08550014]}},
  {'type': 'Feature',
   'properties': {'County': 'Calhoun', 'Positive': 8, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [28.48966896, -96.64708119]}},
  {'type': 'Feature',
   'properties': {'County': 'Walker', 'Positive': 8, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [30.73899492, -95.57224172]}},
  {'type': 'Feature',
   'properties': {'County': 'Polk', 'Positive': 7, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [30.79250963, -94.82994949]}},
  {'type': 'Feature',
   'properties': {'County': 'Hockley', 'Positive': 7, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [33.60750375, -102.3430919]}},
  {'type': 'Feature',
   'properties': {'County': 'Erath', 'Positive': 7, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [32.23640361, -98.21722756]}},
  {'type': 'Feature',
   'properties': {'County': 'Bastrop', 'Positive': 7, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [30.10353518, -97.31187705]}},
  {'type': 'Feature',
   'properties': {'County': 'Moore', 'Positive': 6, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [35.83768863, -101.8929556]}},
  {'type': 'Feature',
   'properties': {'County': 'Wilson', 'Positive': 6, 'Fatalities': 0},
   'geometry': {'type': 'Point',
    'coordinates': [29.17315896, -98.08621015000001]}},
  {'type': 'Feature',
   'properties': {'County': 'Parker', 'Positive': 6, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [32.77852261, -97.80472194]}},
  {'type': 'Feature',
   'properties': {'County': 'Hale', 'Positive': 6, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [34.07051782, -101.8269082]}},
  {'type': 'Feature',
   'properties': {'County': 'Starr', 'Positive': 5, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [26.56212627, -98.73834895]}},
  {'type': 'Feature',
   'properties': {'County': 'Liberty', 'Positive': 5, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [30.15153187, -94.8120925]}},
  {'type': 'Feature',
   'properties': {'County': 'Lamar', 'Positive': 5, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [33.66746186, -95.57110784]}},
  {'type': 'Feature',
   'properties': {'County': 'Harrison', 'Positive': 5, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [32.54814898, -94.37155736]}},
  {'type': 'Feature',
   'properties': {'County': 'Donley', 'Positive': 5, 'Fatalities': 0},
   'geometry': {'type': 'Point',
    'coordinates': [34.96540246, -100.81405009999999]}},
  {'type': 'Feature',
   'properties': {'County': 'Cherokee', 'Positive': 5, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [31.83695632, -95.16515234]}},
  {'type': 'Feature',
   'properties': {'County': 'Navarro', 'Positive': 5, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [32.04695429, -96.47248134]}},
  {'type': 'Feature',
   'properties': {'County': 'Gray', 'Positive': 5, 'Fatalities': 0},
   'geometry': {'type': 'Point',
    'coordinates': [35.40130666000001, -100.812475]}},
  {'type': 'Feature',
   'properties': {'County': 'Val Verde', 'Positive': 5, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [29.89300587, -101.15171]}},
  {'type': 'Feature',
   'properties': {'County': 'Willacy', 'Positive': 5, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [26.47132899, -97.64303323]}},
  {'type': 'Feature',
   'properties': {'County': 'Hill', 'Positive': 5, 'Fatalities': 0},
   'geometry': {'type': 'Point',
    'coordinates': [31.99079033, -97.13241420000001]}},
  {'type': 'Feature',
   'properties': {'County': 'Deaf Smith', 'Positive': 5, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [34.96602014, -102.6048162]}},
  {'type': 'Feature',
   'properties': {'County': 'Terry', 'Positive': 4, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [33.17373729, -102.335157]}},
  {'type': 'Feature',
   'properties': {'County': 'Maverick', 'Positive': 4, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [28.74260943, -100.3144638]}},
  {'type': 'Feature',
   'properties': {'County': 'Panola', 'Positive': 4, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [32.16222886, -94.30552858]}},
  {'type': 'Feature',
   'properties': {'County': 'Coryell', 'Positive': 4, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [31.39087578, -97.7991883]}},
  {'type': 'Feature',
   'properties': {'County': 'San Patricio', 'Positive': 4, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [28.00922186, -97.51859857]}},
  {'type': 'Feature',
   'properties': {'County': 'Cass', 'Positive': 4, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [33.07750446, -94.34348771]}},
  {'type': 'Feature',
   'properties': {'County': 'San Augustine', 'Positive': 4, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [31.39427005, -94.16809762]}},
  {'type': 'Feature',
   'properties': {'County': 'Austin', 'Positive': 4, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [29.88711223, -96.27791829]}},
  {'type': 'Feature',
   'properties': {'County': 'Uvalde', 'Positive': 4, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [29.35669829, -99.76203107]}},
  {'type': 'Feature',
   'properties': {'County': 'Burnet', 'Positive': 4, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [30.78843382, -98.18252382]}},
  {'type': 'Feature',
   'properties': {'County': 'Brown', 'Positive': 4, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [31.77432313, -98.99989649]}},
  {'type': 'Feature',
   'properties': {'County': 'Van Zandt', 'Positive': 4, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [32.56368961, -95.8364862]}},
  {'type': 'Feature',
   'properties': {'County': 'Medina', 'Positive': 3, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [29.35520493, -99.11008331]}},
  {'type': 'Feature',
   'properties': {'County': 'Young', 'Positive': 3, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [33.17670764, -98.68781396]}},
  {'type': 'Feature',
   'properties': {'County': 'Lynn', 'Positive': 3, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [33.17685487, -101.8160235]}},
  {'type': 'Feature',
   'properties': {'County': 'Llano', 'Positive': 3, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [30.70566579, -98.68387398]}},
  {'type': 'Feature',
   'properties': {'County': 'Live Oak', 'Positive': 3, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [28.3514375, -98.12474493]}},
  {'type': 'Feature',
   'properties': {'County': 'Limestone', 'Positive': 3, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [31.54541898, -96.58056718]}},
  {'type': 'Feature',
   'properties': {'County': 'Jackson', 'Positive': 3, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [28.95603133, -96.57883268]}},
  {'type': 'Feature',
   'properties': {'County': 'Hopkins', 'Positive': 3, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [33.14933822, -95.56414173]}},
  {'type': 'Feature',
   'properties': {'County': 'Upshur', 'Positive': 3, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [32.7362827, -94.94132011]}},
  {'type': 'Feature',
   'properties': {'County': 'Eastland', 'Positive': 3, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [32.32739258, -98.8325713]}},
  {'type': 'Feature',
   'properties': {'County': 'Dawson', 'Positive': 3, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [32.74258137, -101.9476136]}},
  {'type': 'Feature',
   'properties': {'County': 'Caldwell', 'Positive': 3, 'Fatalities': 0},
   'geometry': {'type': 'Point',
    'coordinates': [29.83677935, -97.61983479000001]}},
  {'type': 'Feature',
   'properties': {'County': 'Wise', 'Positive': 3, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [33.21585061, -97.65444124]}},
  {'type': 'Feature',
   'properties': {'County': 'Grimes', 'Positive': 3, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [30.54360689, -95.98557334]}},
  {'type': 'Feature',
   'properties': {'County': 'Robertson', 'Positive': 2, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [31.02705415, -96.51272568]}},
  {'type': 'Feature',
   'properties': {'County': 'Trinity', 'Positive': 2, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [31.0885069, -95.13551682]}},
  {'type': 'Feature',
   'properties': {'County': 'Karnes', 'Positive': 2, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [28.90493782, -97.85960621]}},
  {'type': 'Feature',
   'properties': {'County': 'Oldham', 'Positive': 2, 'Fatalities': 1},
   'geometry': {'type': 'Point', 'coordinates': [35.40497586, -102.6029949]}},
  {'type': 'Feature',
   'properties': {'County': 'Kleberg', 'Positive': 2, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [27.43274395, -97.72889778]}},
  {'type': 'Feature',
   'properties': {'County': 'Atascosa', 'Positive': 2, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [28.89418432, -98.52741302]}},
  {'type': 'Feature',
   'properties': {'County': 'Blanco', 'Positive': 2, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [30.26636128, -98.39974086]}},
  {'type': 'Feature',
   'properties': {'County': 'Burleson', 'Positive': 2, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [30.49246139, -96.62109399]}},
  {'type': 'Feature',
   'properties': {'County': 'Colorado', 'Positive': 2, 'Fatalities': 0},
   'geometry': {'type': 'Point', 'coordinates': [29.6208542, -96.52630821]}},
  {'type': 'Feature',
   'properties': {'County': 'Crane', 'Positive': 2, 'Fatalities': 0},

In [95]:

with open('static/js/map.json','w') as f:
    json.dump(javascript_file, f, indent=4, sort_keys=False)

In [96]:
browser.visit(url4)

In [97]:
headlines_harris = browser.html
headline_soup = bs(headlines_harris, 'html.parser')

In [98]:
# lis = headline_soup.find_all('li', class_="headline-list-with-abstract__item")
links = headline_soup.find_all('div', class_="headline-list-with-abstract__headline")

titles = []
hrefs = []

In [99]:
recent = headline_soup.find_all('div', class_="story-snapshot-with-abstract__headline")[0]

In [100]:
recent

<div class="story-snapshot-with-abstract__headline">
<a class="story-snapshot-with-abstract__link" data-tracking="story-snapshot-with-abstract/headlineLinkClicked" href="/article/news/health/coronavirus/coronavirus-austin-cases-of-covid-19-confirmed/285-e7770e57-cf62-4571-a97c-b10216c50cd0">
<div class="story-snapshot-with-abstract__desktop-title dot-ellipsis dot-height-180" style="overflow-wrap: break-word;">
                        Galveston County woman among 2 positive cases of coronavirus confirmed in Austin area
                    </div>
<div class="story-snapshot-with-abstract__mobile-title dot-ellipsis dot-height-135" style="overflow-wrap: break-word;">
                        Galveston County woman among 2 positive cases of coronavirus confirmed in Austin area
                    </div>
</a>
</div>

In [101]:
recent_title = recent.find('div', class_="story-snapshot-with-abstract__desktop-title dot-ellipsis dot-height-180").text.strip()
recent_title

'Galveston County woman among 2 positive cases of coronavirus confirmed in Austin area'

In [102]:
titles.append(recent_title)
hrefs.append('https://www.khou.com' + recent.a['href'])

In [103]:
links

[<div class="headline-list-with-abstract__headline">
 <a class="headline-list-with-abstract__link" data-tracking="headline-list-with-abstract/headlineLinkClicked" href="/article/news/health/coronavirus/coronavirus-updates-houston-live-blog-april-3/285-6d1d2743-5612-4773-8627-3b9622f845d8">
                     Coronavirus updates: Over 80 people test positive at Texas City nursing home
                 </a>
 </div>,
 <div class="headline-list-with-abstract__headline"> <a class="headline-list-with-abstract__link">2020: Simple Method Ends Toenail Fungus - Try It Now!</a> </div>,
 <div class="headline-list-with-abstract__headline">
 <a class="headline-list-with-abstract__link" data-tracking="headline-list-with-abstract/headlineLinkClicked" href="/article/news/health/coronavirus/new-york-gets-chinese-ventilators/285-4d4f73e9-3274-4a9a-88cf-096a7e0a3c3b">
                     New York gets Chinese ventilators; Trump wants more thanks
                 </a>
 </div>,
 <div class="headline-list-with-abstract__headline">
 <a class="headline-list-with-abstract__link" data-tracking="headline-list-with-abstract/headlineLinkClicked" href="/article/news/health/coronavirus/coronavirus-houston-impacts-on-undocumented-immigrants/285-085f2467-5e43-433d-bd85-053732b581d0">
                     Coronavirus impact on local undocumented immigrants unknown
                 </a>
 </div>,
 <div class="headline-list-with-abstract__headline">
 <a class="headline-list-with-abstract__link" data-tracking="headline-list-with-abstract/headlineLinkClicked" href="/article/news/health/coronavirus/trump-believes-nfl-season-will-start-on-time-in-meeting-with-sports-commissioners/285-f10ac0a1-cc35-4885-9f60-9270e6b88fa2">
                     Trump says he believes NFL season will start on time in meeting with sports commissioners
                 </a>
 </div>,
 <div class="headline-list-with-abstract__headline">
 <a class="headline-list-with-abstract__link" data-tracking="headline-list-with-abstract/headlineLinkClicked" href="/article/news/health/coronavirus/coronavirus-updates-houston-blog-live-april-4/285-f799b57f-cb53-47c7-80a4-06c894d89baf">
                     Coronavirus updates: Galveston County reports first death due to COVID-19
                 </a>
 </div>,
 <div class="headline-list-with-abstract__headline">
 <a class="headline-list-with-abstract__link" data-tracking="headline-list-with-abstract/headlineLinkClicked" href="/article/news/health/coronavirus/another-cruise-ship-with-2-virus-deaths-docks-in-florida/285-56817885-0283-4715-8708-b6f72e4892d2">
                     Another cruise ship with virus victims docks in Florida
                 </a>
 </div>]

In [104]:

for article in links:
    
    try:
        
        title = article.find('a', class_="headline-list-with-abstract__link").text
        
        link = article.a['href']
        
        if (title and link):
            
            
            print('-------------')
            print(title)
            print(link)
            titles.append(title.strip())
            hrefs.append('https://www.khou.com' + link)
            
    except:
        print('no')

-------------

                    Coronavirus updates: Over 80 people test positive at Texas City nursing home

/article/news/health/coronavirus/coronavirus-updates-houston-live-blog-april-3/285-6d1d2743-5612-4773-8627-3b9622f845d8
no
-------------

                    New York gets Chinese ventilators; Trump wants more thanks

/article/news/health/coronavirus/new-york-gets-chinese-ventilators/285-4d4f73e9-3274-4a9a-88cf-096a7e0a3c3b
-------------

                    Coronavirus impact on local undocumented immigrants unknown

/article/news/health/coronavirus/coronavirus-houston-impacts-on-undocumented-immigrants/285-085f2467-5e43-433d-bd85-053732b581d0
-------------

                    Trump says he believes NFL season will start on time in meeting with sports commissioners

/article/news/health/coronavirus/trump-believes-nfl-season-will-start-on-time-in-meeting-with-sports-commissioners/285-f10ac0a1-cc35-4885-9f60-9270e6b88fa2
-------------

                    Coronavirus updates: Galveston County reports first death due to COVID-19

/article/news/health/coronavirus/coronavirus-updates-houston-blog-live-april-4/285-f799b57f-cb53-47c7-80a4-06c894d89baf
-------------

                    Another cruise ship with virus victims docks in Florida

/article/news/health/coronavirus/another-cruise-ship-with-2-virus-deaths-docks-in-florida/285-56817885-0283-4715-8708-b6f72e4892d2

In [105]:
latest_headlines_df = pd.DataFrame(list(zip(titles, hrefs)), columns =['Headline', 'link'])

In [106]:
latest_headlines_df

,Headline,link
0,Galveston County woman among 2 positive cases ...,https://www.khou.com/article/news/health/coron...
1,Coronavirus updates: Over 80 people test posit...,https://www.khou.com/article/news/health/coron...
2,New York gets Chinese ventilators; Trump wants...,https://www.khou.com/article/news/health/coron...
3,Coronavirus impact on local undocumented immig...,https://www.khou.com/article/news/health/coron...
4,Trump says he believes NFL season will start o...,https://www.khou.com/article/news/health/coron...
5,Coronavirus updates: Galveston County reports ...,https://www.khou.com/article/news/health/coron...
6,Another cruise ship with virus victims docks i...,https://www.khou.com/article/news/health/coron...

In [107]:
latest_headlines_df.to_csv('static/csv/headlines.csv', index=False, header=True)

In [108]:
browser.quit()